IF(NOT CMAKE_BUILD_TYPE)
    SET(CMAKE_BUILD_TYPE Release ... FORCE)
ENDIF()
SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_C_COMPILER "avr-gcc")
SET(CMAKE_ASM_LINK_EXECUTABLE "avr-ld")
SET(CMAKE_ASM_COMPILER "avr-gcc")
SET(CMAKE_C_FLAGS "-std=gnu99 -Wall -Wstrict-prototypes -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -Os -mmcu=${AVR_MCU}")
include_directories("/usr/avr/include")
MACRO(AVR_CREATE_HEX name)
    MESSAGE("Copying hex...")
    ADD_CUSTOM_COMMAND(TARGET ${name} POST_BUILD COMMAND avr-objcopy ARGS -O ihex -R.eeprom ${CMAKE_BINARY_DIR}/${name} ${CMAKE_SOURCE_DIR}/${name}.hex)
ENDMACRO(AVR_CREATE_HEX)
